import {DEFAULTS,BUILTINS,cleanStyle,renderSticker,canvasBlob,fontCoverage} from './render.js?v=2';
import {FONT_DATA} from './font-data.js?v=2';
import {openStore,get,putMany,toBase64,fromBase64} from './storage.js?v=2';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let state={text:'',style:{...DEFAULTS},favorites:[],fontFavorites:[]}, imported=[], families=[...BUILTINS],faces=new Map(), coverage=new Map(),dbReady=false,fontsReady=false,rendered=null,saveTimer,renderTimer,toastTimer,restoreBusy=false,exportURL;
const publicLoaded=new Set(BUILTINS.filter(f=>f.core).map(f=>f.id)),publicRecords=new Map(),publicPending=new Map();
let fontChoice=0,downloadAllBusy=false;
const presetData=[
 ['極簡黑字','一句，剛剛好。',{font:'sans'},'#f3f5ef','#1b221c'],
 ['極簡白字','留一點空白',{font:'sans',color:'#ffffff'},'#334336','#ffffff'],
 ['柔色標籤','今天很可以',{font:'sans',background:true,bgColor:'#d8ef9a',padding:26,radius:24},'#d8ef9a','#243322'],
 ['深底白字','把日常寫下來',{font:'serif',color:'#ffffff',background:true,bgColor:'#273a2d',radius:8},'#273a2d','#ffffff'],
 ['描邊標題','我的小宇宙',{font:'sans',color:'#ffffff',outline:true,outlineColor:'#344b30',outlineWidth:3},'#e9efe2','#344b30'],
 ['柔和陰影','慢慢，也很好',{font:'kai',color:'#344832',shadow:true,shadowBlur:9,shadowY:7,shadowOpacity:.28},'#eff2eb','#344832'],
 ['圓潤包邊','今天很可愛',{font:'huninn',background:true,bgStyle:'contour',bgColor:'#ffdf63',bgThickness:10},'#fff8d8','#383722'],
 ['手寫螢光筆','寫下小日常',{font:'iansui',background:true,bgStyle:'marker',bgColor:'#d8ef9a',bgOpacity:.65},'#f3f7e9','#344832'],
 ['粗黑雙層貼紙','就是今天！',{font:'chironheihk',background:true,bgStyle:'sticker',bgColor:'#b9caf4',bgInnerColor:'#ffffff',bgInnerWidth:3,bgThickness:10},'#eaf0ff','#25355c'],
 ['波浪短句','一起去看海',{font:'huninn',layout:'wave',waveHeight:18,background:true,bgStyle:'contour',bgColor:'#d0eafa',bgThickness:8},'#edf7fb','#345467'],
 ['階梯標題','步步都算數',{font:'chironheihk',layout:'step',stepHeight:10,background:true,bgStyle:'lines',bgColor:'#ffe2bd',padding:14},'#fff3e4','#614627'],
 ['直排日常','日常\n微光',{font:'kai',layout:'vertical',width:400,size:60,background:true,bgStyle:'marker',bgColor:'#e7d7f0',markerHeight:.7},'#f5edf8','#625170']
];
function toast(message){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').hidden=false;toastTimer=setTimeout(()=>$('#toast').hidden=true,4200);}
function errorMessage(e,fallback='操作未完成，請再試一次。'){console.error(e);if(e instanceof SyntaxError||e instanceof RangeError)return '檔案內容無法讀取，請選擇完整且有效的檔案。';return e instanceof Error&&e.message&&!/indexed|quota|transaction/i.test(e.message)?e.message:fallback;}
function ask(title,body,initial){return new Promise(resolve=>{const d=$('#message-dialog');$('#message-title').textContent=title;$('#message-body').textContent=body;$('#message-input-label').hidden=initial===undefined;$('#message-input').value=initial??'';d.returnValue='cancel';d.onclose=()=>resolve(d.returnValue==='ok'?(initial===undefined?true:$('#message-input').value.trim()):null);d.showModal();});}
function safeState(v){if(!v||typeof v!=='object'||typeof v.text!=='string'||v.text.length>2500||!Array.isArray(v.favorites)||v.favorites.length>100)throw new Error('這份備份的內容格式不正確。');return{text:v.text,style:cleanStyle(v.style),fontFavorites:Array.isArray(v.fontFavorites)?[...new Set(v.fontFavorites.filter(x=>typeof x==='string'&&/^[a-zA-Z0-9_-]{1,90}$/.test(x)))].slice(0,50):[],favorites:v.favorites.map(f=>{if(!f||typeof f.name!=='string'||!f.name.trim()||f.name.length>40)throw new Error('收藏名稱格式不正確。');return{id:crypto.randomUUID(),name:f.name,style:cleanStyle(f.style)};})};}
async function persist(){if(!dbReady||restoreBusy)return;try{await putMany([['state',structuredClone(state)]]);$('#save-state').textContent='已保存在這台裝置';}catch(e){$('#save-state').textContent='尚未保存，請先匯出備份';toast('裝置空間不足或無法保存，請先匯出備份。');}}
function changed(){clearTimeout(saveTimer);saveTimer=setTimeout(persist,350);scheduleRender();}
function scheduleRender(){clearTimeout(renderTimer);renderTimer=setTimeout(draw,70);}
function draw(){
 $('#copy-image').disabled=$('#save-image').disabled=true;rendered=null;
 if(!state.text.trim()){$('#preview').hidden=true;$('#empty-preview').hidden=false;$('#dimensions').textContent='透明背景 · PNG 圖片';$('#render-warning').hidden=true;return;}
 if(!fontsReady||BUILTINS.some(f=>f.id===state.style.font&&!publicLoaded.has(f.id))){$('#preview').hidden=true;$('#empty-preview').hidden=true;$('#render-warning').hidden=false;$('#render-warning').textContent='這款字體尚未就緒，請到「字體」點選下載。';return;}
 try{rendered=renderSticker(state.text,state.style,families);const c=$('#preview');c.width=rendered.width;c.height=rendered.height;c.getContext('2d').drawImage(rendered.canvas,0,0);c.hidden=false;$('#empty-preview').hidden=true;$('#dimensions').textContent=`${c.width} × ${c.height} · PNG`;
 const warnings=[];if(rendered.scaled)warnings.push('長篇內容已降低輸出倍率，建議分成兩張貼紙。');const covers=coverage.get(state.style.font);if(covers&&Array.from(state.text).some(c=>!/[\s\p{Extended_Pictographic}\p{Regional_Indicator}\u200d\ufe0f\p{Emoji_Modifier}]/u.test(c)&&!covers(c.codePointAt(0))))warnings.push('這個字體缺少部分文字，已使用內建字體補上。');$('#render-warning').hidden=!warnings.length;$('#render-warning').textContent=warnings.join(' ');$('#copy-image').disabled=$('#save-image').disabled=false;
 }catch(e){$('#preview').hidden=true;$('#render-warning').hidden=false;$('#render-warning').textContent=errorMessage(e);}
}
function updateControls(){for(const [key,val]of Object.entries(state.style)){const el=document.getElementById(key);if(!el)continue;if(el.type==='checkbox')el.checked=val;else el.value=val;const output=document.getElementById(key+'-value');if(output)output.textContent=displayValue(key,val);}$$('[data-align]').forEach(b=>b.classList.toggle('active',b.dataset.align===state.style.align));$('#background-controls').hidden=!state.style.background;$('#outline-controls').hidden=!state.style.outline;$('#shadow-controls').hidden=!state.style.shadow;updateV2Controls();renderFontList();}
const displayValue=(key,v)=>['bgOpacity','shadowOpacity','markerHeight','markerOffset'].includes(key)?Math.round(v*100)+'%':key==='lineHeight'?Number(v).toFixed(2):v;
function slider(parent,key,label,min,max,step=1){const wrap=document.createElement('div');wrap.className='control';const l=document.createElement('label');l.htmlFor=key;l.append(document.createTextNode(label));const out=document.createElement('output');out.id=key+'-value';out.htmlFor=key;l.append(out);const input=document.createElement('input');Object.assign(input,{type:'range',id:key,min,max,step});wrap.append(l,input);$(parent).append(wrap);}
[['size','字級',20,140],['width','文字區寬度',160,1200,10],['spacing','字距',0,16],['lineHeight','行距',1,2.5,.05]].forEach(x=>slider('#layout-controls',...x));
[['bgOpacity','底色透明度',0,1,.05],['radius','圓角',0,100],['padding','周圍留白',0,100]].forEach(x=>slider('#bg-sliders',...x));
[['bgThickness','包邊厚度',1,40],['bgInnerWidth','內層厚度',1,12],['markerHeight','色帶厚度',.1,1.2,.05],['markerOffset','色帶位置',-.5,.5,.05]].forEach(x=>slider('#bg-sliders',...x));
[['waveHeight','起伏大小',0,80],['wavePeriod','每個波浪的字數',2,16,.5]].forEach(x=>slider('#wave-controls',...x));
slider('#step-controls','stepHeight','每字高度差',0,30);
function updateV2Controls(){
 const s=state.style,vertical=s.layout==='vertical';$('#wave-controls').hidden=s.layout!=='wave';$('#step-controls').hidden=s.layout!=='step';
 $('#layout-note').textContent={plain:'依寬度自動換行，也可以自己換行。',wave:'每一行重新起伏，字本身維持正立。',step:'每一行重新開始，調到 0 就回到平直。',vertical:'由上往下、由右往左。英數逐字正立，換行會另起一列。'}[s.layout];
 for(const [key,label]of [['width',vertical?'每列高度':'文字區寬度'],['lineHeight',vertical?'列距':'行距']])document.querySelector(`label[for="${key}"]`).firstChild.textContent=label;
 for(const b of $$('[data-align]'))b.textContent=vertical?{left:'靠上',center:'置中',right:'靠下'}[b.dataset.align]:{left:'靠左',center:'置中',right:'靠右'}[b.dataset.align];
 const contour=['contour','sticker'].includes(s.bgStyle);for(const [key,show]of Object.entries({bgThickness:contour,bgInnerWidth:s.bgStyle==='sticker',markerHeight:s.bgStyle==='marker',markerOffset:s.bgStyle==='marker',radius:!contour,padding:!contour&&s.bgStyle!=='marker'}))document.getElementById(key).closest('.control').hidden=!show;
 $('#inner-color-row').hidden=s.bgStyle!=='sticker';$('#background-note').textContent={label:'包住整組文字，圓角調大可做膠囊標籤。',contour:'沿文字與 emoji 的輪廓包邊。厚度太大時可調小，保留筆畫空隙。',sticker:'內層與外緣可分別選色，像剪下來的小貼紙。',lines:vertical?'每列各有一條底色。':'每行依文字長度加底色，也會跟著起伏。',connected:'相鄰色塊連接，拉大行距或列距可分開。',marker:vertical?'直向色帶，可調厚度與左右位置。':'色帶位於文字後方，可調厚度與上下位置。'}[s.bgStyle];
}
slider('#outline-sliders','outlineWidth','外框粗細',1,12);
[['shadowOpacity','陰影濃淡',0,1,.05],['shadowBlur','柔和程度',0,40],['shadowX','左右位移',-40,40],['shadowY','上下位移',-40,40]].forEach(x=>slider('#shadow-sliders',...x));
for(const key of Object.keys(DEFAULTS)){const el=document.getElementById(key);if(!el)continue;el.addEventListener('input',()=>{state.style[key]=el.type==='checkbox'?el.checked:el.type==='range'?Number(el.value):el.value;updateControls();$$('.preset').forEach(b=>b.classList.remove('active'));changed();});}
$$('[data-align]').forEach(b=>b.onclick=()=>{state.style.align=b.dataset.align;updateControls();changed();});
$$('[data-tab]').forEach(b=>b.onclick=()=>{$$('[data-tab]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-selected',x===b);});$$('.panel').forEach(p=>p.hidden=p.id!=='panel-'+b.dataset.tab);if(b.dataset.tab==='fonts')renderFontList();});
$$('[data-stage]').forEach(b=>b.onclick=()=>{$('#preview-stage').dataset.mode=b.dataset.stage;$$('[data-stage]').forEach(x=>x.classList.toggle('active',x===b));});
presetData.forEach(([name,sample,style,bg,color],index)=>{const b=document.createElement('button');b.className='preset';const art=document.createElement('span');art.className='preset-art';art.setAttribute('aria-label',sample);art.style.backgroundImage='url(./preset-sheet.webp)';art.style.backgroundSize='200% 600%';art.style.backgroundPosition=`${index%2*100}% ${Math.floor(index/2)/5*100}%`;const label=document.createElement('span');label.className='preset-label';label.textContent=name;b.append(art,label);b.onclick=async()=>{const choice=++fontChoice;try{await ensurePublicFont(style.font||'sans');if(choice!==fontChoice)return;}catch(e){toast(errorMessage(e));return;}state.style={...DEFAULTS,...style};$$('.preset').forEach(x=>x.classList.toggle('active',x===b));updateControls();changed();};$('#presets').append(b);});
['#181c19','#ffffff','#365b3c','#a34435','#446c91','#b59348','#b49cc7','#d8ef9a'].forEach(color=>{const b=document.createElement('button');b.style.background=color;b.setAttribute('aria-label','文字色 '+color);b.onclick=()=>{state.style.color=color;updateControls();changed();};$('#swatches').append(b);});
function fontIsReady(f){return !!f.buffer||publicLoaded.has(f.id);}
function setPublicCoverage(f){const ranges=FONT_DATA[f.id]?.ranges;if(ranges)coverage.set(f.id,cp=>{let a=0,b=ranges.length-1;while(a<=b){const m=(a+b)>>1;if(cp<ranges[m][0])b=m-1;else if(cp>ranges[m][1])a=m+1;else return true;}return false;});}
async function mountPublic(f,buffer){const face=new FontFace(f.family,buffer);await face.load();document.fonts.add(face);publicLoaded.add(f.id);setPublicCoverage(f);}
async function ensurePublicFont(id){
 const f=BUILTINS.find(f=>f.id===id);if(!f||publicLoaded.has(id))return;if(publicPending.has(id))return publicPending.get(id);
 const work=(async()=>{if(!dbReady)throw new Error('本機保存未就緒，請重新開啟後下載字體。');
 $('#font-download-status').textContent='正在下載 '+f.name+'…';renderFontList();
 try{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),90000);let buffer;try{const response=await fetch('./'+f.file,{signal:controller.signal});if(!response.ok)throw new Error('字體下載未完成，請連網後再試。');buffer=await response.arrayBuffer();}finally{clearTimeout(timer);}if(buffer.byteLength!==FONT_DATA[id]?.bytes)throw new Error('字體檔案不完整，請重新下載。');
 // Validate before committing to local storage; do not mark offline-ready on a failed write.
 const face=new FontFace(f.family,buffer);await face.load();await putMany([['publicFont:'+id,{id,buffer}]]);document.fonts.add(face);publicRecords.set(id,{id,buffer});publicLoaded.add(id);setPublicCoverage(f);$('#font-download-status').textContent=f.name+' · 可離線使用';
 }catch(e){$('#font-download-status').textContent='下載未完成，原有作品保留。連網後可再試。';throw new Error('字體下載或保存未完成，請確認網路與裝置空間後再試。');}
 })();publicPending.set(id,work);renderFontList();try{await work;}finally{publicPending.delete(id);renderFontList();}
}
function renderFontList(){const list=$('#font-list'),filter=$('#font-filter').value;list.replaceChildren();for(const f of families){if(filter==='favorite'&&!state.fontFavorites.includes(f.id)||filter==='local'&&!f.buffer||!['all','favorite','local'].includes(filter)&&f.category!==filter)continue;
 const row=document.createElement('div');row.className='font-card'+(state.style.font===f.id?' active':'');const b=document.createElement('button');b.className='font-select';const strong=document.createElement('strong'),ready=fontIsReady(f);
 if(ready){strong.style.fontFamily=`"${f.family}",NoteSans,sans-serif`;strong.textContent=state.text.split('\n')[0].slice(0,30)||'今天，剛剛好。 Hello';}else strong.textContent=f.name;
 const small=document.createElement('small');small.textContent=f.name+' · '+(f.buffer?'本機字體':f.chinese?'支援繁中、英文':'英文款・中文使用基本字體')+(f.note?' · '+f.note:'');const hint=document.createElement('span');hint.className='download-label';hint.textContent=publicPending.has(f.id)?'下載中…':ready?'可離線使用':`點選下載 · 約 ${((FONT_DATA[f.id]?.bytes||0)/1048576).toFixed(1)} MB · 下載後顯示你的文字`;
 b.append(strong,small,hint);b.onclick=async()=>{const choice=++fontChoice;try{await ensurePublicFont(f.id);if(choice!==fontChoice)return;state.style.font=f.id;updateControls();changed();}catch(e){toast(errorMessage(e));}};row.append(b);
 const star=document.createElement('button');star.className='font-star';star.textContent=state.fontFavorites.includes(f.id)?'★':'☆';star.setAttribute('aria-label','常用字體 '+f.name);star.setAttribute('aria-pressed',state.fontFavorites.includes(f.id));star.onclick=()=>{state.fontFavorites=state.fontFavorites.includes(f.id)?state.fontFavorites.filter(x=>x!==f.id):[...state.fontFavorites,f.id];renderFontList();changed();};row.append(star);
 if(f.buffer){const del=document.createElement('button');del.className='small-action';del.textContent='刪除';del.setAttribute('aria-label','刪除字體 '+f.name);del.onclick=()=>removeFont(f);row.append(del);}list.append(row);
 }if(!list.children.length){const p=document.createElement('p');p.className='panel-note';p.textContent='這裡還沒有字體，點字體旁的星星即可加入常用。';list.append(p);}}
$('#font-filter').onchange=renderFontList;
$('#download-fonts').onclick=async()=>{if(downloadAllBusy)return;const pending=BUILTINS.filter(f=>!publicLoaded.has(f.id));if(!pending.length){toast('全部字體都已可離線使用。');return;}const mb=pending.reduce((n,f)=>n+FONT_DATA[f.id].bytes,0)/1048576;if(!await ask('下載全部字體？',`約 ${mb.toFixed(1)} MB，完成後這些字體都能離線使用。請保持網路連線。`))return;downloadAllBusy=true;$('#download-fonts').disabled=true;let done=0;try{for(const f of pending){$('#download-fonts').textContent=`下載 ${done+1} / ${pending.length}`;await ensurePublicFont(f.id);done++;}toast('全部字體已可離線使用。');draw();}catch(e){toast(errorMessage(e));}finally{downloadAllBusy=false;$('#download-fonts').disabled=false;$('#download-fonts').textContent='下載全部字體';}};
function renderFavorites(){const root=$('#favorites');root.replaceChildren();if(!state.favorites.length){const p=document.createElement('p');p.className='empty-favorites';p.textContent='把喜歡的搭配留下來，下次直接套用。';root.append(p);return;}for(const f of state.favorites){const row=document.createElement('div');row.className='favorite-row';const apply=document.createElement('button');apply.className='favorite-apply';apply.textContent=f.name;apply.onclick=async()=>{const choice=++fontChoice;try{await ensurePublicFont(f.style.font);if(choice!==fontChoice)return;}catch(e){toast(errorMessage(e));return;}state.style={...f.style};if(!families.some(x=>x.id===state.style.font)){state.style.font='sans';toast('原字體已移除，改用內建黑體。');}updateControls();changed();};const rename=document.createElement('button');rename.className='small-action';rename.textContent='改名';rename.onclick=async()=>{const name=await ask('收藏名稱','最多 40 個字。',f.name);if(name){f.name=name;renderFavorites();changed();}};const del=document.createElement('button');del.className='small-action';del.textContent='刪除';del.onclick=async()=>{if(await ask('刪除收藏？','目前的文字與樣式會保留。')){state.favorites=state.favorites.filter(x=>x.id!==f.id);renderFavorites();changed();}};row.append(apply,rename,del);root.append(row);}}
$('#save-style').onclick=async()=>{if(state.favorites.length>=100){toast('收藏已達 100 款，請先整理後再新增。');return;}const name=await ask('收藏目前風格','之後套用時，會保留你新輸入的文字。','我的風格');if(name){state.favorites.push({id:crypto.randomUUID(),name,style:{...state.style}});renderFavorites();changed();toast('已加入收藏');}};
$('#text').addEventListener('input',e=>{state.text=e.target.value;if(!$('#panel-fonts').hidden)renderFontList();changed();});
$('#new-text').onclick=async()=>{if(state.text&&!await ask('開始新的文字？','目前草稿會清空。收藏與匯入字體會保留。'))return;state.text='';$('#text').value='';changed();$('#text').focus();};
$('#settings-open').onclick=()=>$('#settings-dialog').showModal();$$('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());
async function loadImported(f){const cv=fontCoverage(f.buffer);const face=new FontFace(f.family,f.buffer);await face.load();document.fonts.add(face);faces.set(f.id,face);coverage.set(f.id,cv);return f;}
function rebuildFamilies(){families=[...BUILTINS,...imported];}
async function removeFont(f){if(!await ask('刪除這個字體？','使用它的目前樣式與收藏將改用內建黑體。'))return;const next=imported.filter(x=>x.id!==f.id);const nextState=structuredClone(state);nextState.fontFavorites=nextState.fontFavorites.filter(x=>x!==f.id);if(nextState.style.font===f.id)nextState.style.font='sans';nextState.favorites.forEach(x=>{if(x.style.font===f.id)x.style.font='sans';});try{if(!dbReady)throw new Error('目前無法保存變更。');await putMany([['fonts',next],['state',nextState]]);imported=next;state=nextState;document.fonts.delete(faces.get(f.id));faces.delete(f.id);coverage.delete(f.id);rebuildFamilies();updateControls();draw();toast('字體已刪除');}catch(e){toast(errorMessage(e,'無法刪除，請稍後再試。'));}}
$('#import-font').onclick=()=>$('#font-file').click();
$('#font-file').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(!dbReady)throw new Error('本機保存尚未就緒，請重新開啟網頁。');if(!/\.(ttf|otf)$/i.test(file.name)||file.size>20*1024*1024||file.size<20)throw new Error('請選擇 20 MB 以下的 TTF 或 OTF 字體。');if(imported.reduce((n,f)=>n+f.buffer.byteLength,0)+file.size>80*1024*1024)throw new Error('匯入字體總容量最多 80 MB，請先整理不需要的字體。');if(imported.length>=20)throw new Error('最多匯入 20 個字體，請先刪除不需要的字體。');const buffer=await file.arrayBuffer(),hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',buffer)),b=>b.toString(16).padStart(2,'0')).join('');if(imported.some(f=>f.hash===hash)){toast('這個字體已經匯入過了。');return;}const id='font_'+crypto.randomUUID().replaceAll('-',''),f={id,family:id,name:file.name.replace(/\.(ttf|otf)$/i,'').slice(0,80),hash,buffer};await loadImported(f);try{await putMany([['fonts',[...imported,f]]]);}catch(e){document.fonts.delete(faces.get(id));faces.delete(id);coverage.delete(id);throw e;}imported.push(f);rebuildFamilies();state.style.font=f.id;updateControls();changed();toast('字體已匯入，只保存在這台裝置。');}catch(e){toast(errorMessage(e,'裝置空間不足，請整理字體或先備份。'));}};
function currentCanvas(){draw();if(!rendered)throw new Error('請先輸入文字，並等待字體載入。');return rendered.canvas;}
$('#copy-image').onclick=()=>{try{const canvas=currentCanvas();if(!navigator.clipboard?.write||!window.ClipboardItem)throw new Error('這個瀏覽器無法複製圖片，請改用 Safari 或儲存圖片。');const item=new ClipboardItem({'image/png':canvasBlob(canvas)});navigator.clipboard.write([item]).then(()=>toast('已複製貼紙，現在可以切到 IG 貼上。')).catch(()=>toast('圖片複製未成功，請允許複製或改用儲存圖片。'));}catch(e){toast(errorMessage(e));}};
let shareFile;
$('#save-image').onclick=async()=>{try{const blob=await canvasBlob(currentCanvas());if(exportURL)URL.revokeObjectURL(exportURL);exportURL=URL.createObjectURL(blob);$('#export-image').src=exportURL;$('#download-image').href=exportURL;shareFile=new File([blob],'inknote-'+new Date().toISOString().slice(0,10)+'.png',{type:'image/png'});$('#download-image').download=shareFile.name;$('#share-file').hidden=!navigator.canShare?.({files:[shareFile]});$('#export-dialog').showModal();}catch(e){toast(errorMessage(e));}};
$('#share-file').onclick=async()=>{try{await navigator.share({files:[shareFile]});}catch(e){if(e.name!=='AbortError')toast('分享未完成，可改按下載 PNG 或長按圖片。');}};
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
$('#backup').onclick=()=>{try{const data={app:'inknote',version:2,createdAt:new Date().toISOString(),state,fonts:imported.map(({buffer,...f})=>({...f,data:toBase64(buffer)}))};download(new Blob([JSON.stringify(data)],{type:'application/json'}),'inknote-backup-'+new Date().toISOString().slice(0,10)+'.json');toast('已交給瀏覽器下載。備份含私人內容，請妥善保存。');}catch(e){toast('備份未完成，請先減少不需要的字體後重試。');}};
$('#restore').onclick=()=>$('#restore-file').click();
$('#restore-file').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;let candidates=[],candidateFaces=[];try{if(!dbReady)throw new Error('本機保存尚未就緒，請重新開啟網頁。');if(file.size>150*1024*1024)throw new Error('備份檔太大，目前最多支援 150 MB。');const data=JSON.parse(await file.text());if(data.app!=='inknote'||![1,2].includes(data.version)||!Array.isArray(data.fonts)||data.fonts.length>20)throw new Error('請選擇由字在匯出的備份檔。');const next=safeState(data.state);const ids=new Set();for(const f of data.fonts){if(!/^font_[a-f0-9]{32}$/.test(f.id)||ids.has(f.id)||typeof f.name!=='string'||f.name.length>80)throw new Error('字體清單格式不正確。');ids.add(f.id);const buffer=fromBase64(f.data);if(buffer.byteLength>20*1024*1024)throw new Error('備份字體過大。');fontCoverage(buffer);const face=new FontFace(f.id,buffer);await face.load();candidateFaces.push(face);const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',buffer)),b=>b.toString(16).padStart(2,'0')).join('');candidates.push({id:f.id,family:f.id,name:f.name,hash,buffer});}if(candidates.reduce((n,f)=>n+f.buffer.byteLength,0)>80*1024*1024)throw new Error('備份字體總容量超過 80 MB。');const valid=new Set([...BUILTINS.map(f=>f.id),...ids]);if(!valid.has(next.style.font)||next.favorites.some(f=>!valid.has(f.style.font)))throw new Error('備份缺少使用中的字體，已取消還原。');if(!await ask('還原這份備份？',`將取代目前草稿、${state.favorites.length} 款收藏及 ${imported.length} 個匯入字體。建議先備份目前資料。`))return;restoreBusy=true;clearTimeout(saveTimer);await putMany([['fonts',candidates],['state',next]]);for(const face of faces.values())document.fonts.delete(face);faces.clear();coverage.clear();imported=candidates;state=next;for(let i=0;i<candidates.length;i++){document.fonts.add(candidateFaces[i]);faces.set(candidates[i].id,candidateFaces[i]);coverage.set(candidates[i].id,fontCoverage(candidates[i].buffer));}BUILTINS.filter(f=>publicLoaded.has(f.id)).forEach(setPublicCoverage);rebuildFamilies();$('#text').value=state.text;updateControls();renderFavorites();draw();toast(BUILTINS.some(f=>f.id===state.style.font&&!publicLoaded.has(f.id))?'備份已還原。使用中的公開字體請到「字體」重新下載。':'備份已還原。');}catch(e){toast(errorMessage(e,'備份無法讀取或空間不足；原有資料已保留。'));}finally{restoreBusy=false;}};
async function prepareOffline(){const status=$('#offline-status');$('#retry-offline').hidden=true;try{if(!('serviceWorker'in navigator))throw new Error();const reg=await navigator.serviceWorker.register('./sw.js',{scope:'./'});await Promise.race([navigator.serviceWorker.ready,new Promise((_,reject)=>setTimeout(reject,90000))]);const cache=await caches.open('inknote-v2');const ready=await cache.match(new URL('./offline-ready',location.href).href);if(!ready){const worker=reg.installing||reg.waiting||reg.active;if(worker&&worker.state!=='activated')await new Promise((resolve,reject)=>{const timeout=setTimeout(reject,120000);worker.addEventListener('statechange',()=>{if(worker.state==='activated'){clearTimeout(timeout);resolve();}if(worker.state==='redundant'){clearTimeout(timeout);reject();}});});}if(!await cache.match(new URL('./offline-ready',location.href).href))throw new Error();status.textContent='離線已準備好 · 基本 3 款字體 · 資料在本機';}catch(e){status.textContent='離線尚未準備完成';$('#retry-offline').hidden=false;}}
$('#retry-offline').onclick=prepareOffline;
if('serviceWorker' in navigator){let updating=!!navigator.serviceWorker.controller;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(updating){toast('新版本已準備好，重新開啟即可使用。');}updating=true;});}
document.addEventListener('visibilitychange',()=>{if(document.hidden){clearTimeout(saveTimer);persist();}});
async function init(){try{await openStore();dbReady=true;const [saved,fs]=await Promise.all([get('state'),get('fonts')]);if(saved)state=safeState(saved);for(const f of fs||[]){try{await loadImported(f);imported.push(f);}catch(e){toast('有一個已保存字體無法載入，請重新匯入。');}}for(const f of BUILTINS.filter(f=>!f.core)){const record=await get('publicFont:'+f.id);if(record){try{await mountPublic(f,record.buffer);publicRecords.set(f.id,record);}catch{toast(f.name+' 需重新下載。');}}}rebuildFamilies();if(!families.some(f=>f.id===state.style.font))state.style.font='sans';}catch(e){dbReady=false;$('#save-state').textContent='無法讀取本機資料，請先備份';toast('本機資料未完整載入，請勿清除網站資料。');}$('#text').value=state.text;renderFavorites();updateControls();try{await Promise.all(BUILTINS.filter(f=>f.core).map(f=>document.fonts.load(`24px ${f.family}`)));fontsReady=true;}catch(e){toast('內建字體載入失敗，請連網後重新開啟。');}draw();prepareOffline();}
init();
